version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "npm"
    directory: "/web/js"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "America/Denver"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
