name: CI
on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'

jobs:
  test:
    name: Run Tests
    permissions:
      contents: read
      checks: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.8.0
        with:
          channel: 'stable'
          flutter-version: '3.7.x'

      - name: Install lcov
        run: sudo apt-get install -y lcov

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze Code
        run: dart analyze --fatal-infos

      - name: Dart Code Metrics
        run: dart run dart_code_metrics:metrics analyze --reporter=github --fatal-style --fatal-performance --fatal-warnings lib

      - name: Run unit / integration tests
        run: flutter test --coverage

      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v3
        with:
          coverage-files: ./coverage/lcov.info
          minimum-coverage: 90
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true

      - name: Upload coverage report
        if: ${{ github.ref_name == 'main' && always() }}
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info

      - name: Test report
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Unit/Integration Test Report
          path: tests.json
          reporter: flutter-json
          fail-on-error: true
